app = "patrickhume-reactivities"
primary_region = "lhr"

[build]
  image = "patrickhume/reactivities:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  Cloudinary__CloudName="dpb4uguv6"
  Cloudinary__ApiKey="475982561961457"
  Ethereal__EMail="mireya25@ethereal.email"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]